application: treeplotter
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /admin/.*
  script: main.app
  secure: always
  
- url: /login
  script: main.app
  secure: always

- url: /signup
  script: main.app
  secure: always
  
- url: /forgot
  script: main.app
  secure: always
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
