application: treeplotter
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

- url: /admin/.*
  script: main.app
  secure: always

- url: /home
  script: main.app
  
- url: /login
  script: main.app
  secure: always

- url: /signup
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
